name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    name: Use Node.js ${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.9.5
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
      - name: Install
        run: pnpm install --no-frozen-lockfile
      - name: Lint
        run: pnpm lint
  deadcode:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18.x]
    name: Use Node.js ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.9.5
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
      - name: Install
        run: pnpm install --no-frozen-lockfile
      - name: Detect dead codes
        run: pnpm deadcode
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14.18, 16.x, 18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.23.6
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
      - name: Install
        run: pnpm install --no-frozen-lockfile
      - name: Test
        run: pnpm test
  deploy:
    needs:
      - lint
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.9.5
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Install
        run: pnpm install --no-frozen-lockfile
      - name: Build docs
        run: pnpm docs:build
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist
  edge-release:
    needs:
      - lint
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.9.3
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
      - name: Release Edge
        if: |
          github.event_name == 'push' &&
          !contains(github.event.head_commit.message, '[skip-release]') &&
          !contains(github.event.head_commit.message, 'chore') &&
          !startsWith(github.event.head_commit.message, 'release') &&
          !contains(github.event.head_commit.message, 'docs')
        run: ./scripts/release.sh
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          PNPM_INSTALL: 'true'
          EDGE_RELEASE: 'true'
