name: Release

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.9.3

      - name: Extract version tag
        if: startsWith( github.ref, 'refs/tags/v' )
        uses: jungwinter/split@v2
        id: split
        with:
          msg: ${{ github.ref }}
          separator: '/'

      - name: Create Github Release
        run: gh release create ${{ steps.split.outputs._2 }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate changelog
        run: |
          git restore --source=HEAD --staged --worktree -- package.json pnpm-lock.yaml
          pnpm install --no-frozen-lockfile
          pnpm changelog --tag=${{ steps.split.outputs._2 }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changelog
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          file_pattern: 'CHANGELOG.md'
          commit_message: 'chore: sync changelog'

      - name: Publish package
        run: ./scripts/release.sh
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
